config/routes.rb
Rails.application.routes.draw do
  resources :balance_informations
  resources :aboute_posts
  resources :social_posts
  resources :size_pays
  resources :social_services
  resources :payment_infos
  resources :questions
  resources :question_groups
  mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
 
 
  match '/home', to: 'esrc_zbp#homes', via: 'get'
  match '/signup',  to: 'users#new',  via: 'get'
  match '/contacts',  to: 'esrc_zbp#contacts',  via: 'get'
  
  get '/googlee92ee49ba651f9de', :to => redirect('/googlee92ee49ba651f9de.html')

  get '/robots.txt' => 'esrc_zbp#robots'

  resources :articles
  match '/articles',  to: 'esrc_zbp#articles',  via: 'get'
  
  resources :services
  match '/services',  to: 'esrc_zbp#services',  via: 'get'

  resources :servicetexts
  match '/servicetexts',  to: 'esrc_zbp#servicetexts',  via: 'get'

  resources :users
  match '/users',  to: 'esrc_zbp#users',  via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :filials
  match '/filials', to: 'esrc_zbp#filials', via: 'get'

  resources :aboutes
  get '/aboutes', to:  redirect('/aboutes/1'), via: 'get'

  resources :votes
  match '/votes', to: 'esrc_zbp#votes', via: 'get'

  resources :news
  match '/news', to: 'esrc_zbp#news', via: 'get'

  resources :answerposts do
    collection do
    get :index_admin
    end
    member do
    get :answer
    end  
  end
  match '/answerposts', to: 'esrc_zbp#answerposts', via: 'get'

end

app/models/aboute.rb
class Aboute < ActiveRecord::Base
  has_many :aboute_posts, dependent: :destroy
  validates :text, presence: true
end

app/models/aboute_post.rb
class AboutePost < ActiveRecord::Base
  belongs_to :aboute
  validates :title, presence: true
  validates :text, presence: true
end

app/models/answerpost.rb
class Answerpost < ActiveRecord::Base
	belongs_to :user
end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
end

app/models/balance_information.rb
class BalanceInformation < ActiveRecord::Base
  validates :title, presence: true, length: {minimum: 5}
  validates :content, presence: true
end

app/models/filial.rb
class Filial < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
end

app/models/new.rb
class New < ActiveRecord::Base
end

app/models/payment_info.rb
class PaymentInfo < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :question_group
end

app/models/question_group.rb
class QuestionGroup < ActiveRecord::Base
  has_many :questions
  validates :name, :presence => true
end

app/models/service.rb
class Service < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
  has_many :servicetexts
end

app/models/servicetext.rb
class Servicetext < ActiveRecord::Base
	belongs_to :services
end

app/models/size_pay.rb
class SizePay < ActiveRecord::Base
end

app/models/social_post.rb
class SocialPost < ActiveRecord::Base
  belongs_to :social_service
  validates :title, presence: true
  validates :text, presence: true
end

app/models/social_service.rb
class SocialService < ActiveRecord::Base
  has_many :social_posts, dependent: :destroy
  accepts_nested_attributes_for :social_posts, :allow_destroy => true
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answerposts
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX, message: "имеет не допустимый формат" },
                    uniqueness: { case_sensitive: false, message: "уже существует" }
  has_secure_password
  validates :password, length: { message: "/ Пароль должен быть не менее 6 символов", minimum: 6 }
  validates :password_confirmation, length: { message: "/ пароль и повторный пароль не совпадает", minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :sign_in_admin, only: [:edit, :update, :destroy]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def index
    @article = Article.last(3).reverse
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def robots
    render text: 'robots'
    # robots = File.read(Rails.root + 'config/robots.#{Rails.env}.txt')
    # render :text => robots, :layout => false, :content_type => 'text/plain'
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def sign_in_admin
    redirect_to root_url, notice: 'Страница не найдена' unless sign_in_admin?
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def new
		@new = New.new
	end
	def create
		@new = New.new(new_params)
		if @new.save
    redirect_to @new
  		else
    render 'new'
  		end
	end
	def show
		@new = New.find(params[:id])
	end
	def index
		@new = New.all
	end
	def edit
		@new = New.find(params[:id])
	end
	def update
		@new = New.find(params[:id])
		if @new.update(new_params)
			redirect_to @new
		else
			render 'edit'
		end
	end

	def destroy
  		@new = New.find(params[:id])
 		redirect_to @new if @new.destroy 
  	end

private
	def new_params
	params.require(:new).permit(:title, :text)
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :sign_in_admin, only: [:edit, :update, :destroy, :new]

	def new
		@service = Service.new
	end

	def create
		@service = Service.new(service_params)
		if @service.save
    	redirect_to @service
  	else
    	render 'new'
  	end
	end

	def show
		@service = Service.find(params[:id]).servicetexts
		@content = Service.find(params[:id])
	end

	def index
		@service = Service.all.sort_by { |x| x.type_service }.reverse
	end

	def edit
		@service = Service.find(params[:id])
	end

	def update
		@service = Service.find(params[:id])
		if @service.update(service_params)
			redirect_to @service
		else
			render 'edit'
		end
	end

	def destroy
  	@service = Service.find(params[:id])
 		redirect_to @service if @service.destroy
  end

private
	def service_params
		params.require(:service).permit(:title, :text, :position, :type_service)
	end

	def sign_in_admin
    redirect_to root_url, notice: "Страница не найдена" unless sign_in_admin? || sign_in_editor?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = 'ГКУ "КЦСЗН" Забайкальского края официальный сайт'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def meta_description(content)
    strip_tags(content[0..255]).tr('&nbsp;', ' ').tr('&quot;', '').strip.squeeze
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_in?
    current_user
  end

  def sign_in_admin?
    current_user && current_user.role && current_user.role == "administrator"
  end

  def sign_in_respondent?
    current_user && current_user.role && current_user.role.split(',').include?("respondent")
  end

  def sign_in_editor?
    current_user && current_user.role && current_user.role.split(',').include?("editor")
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/services/edit.html.erb
<% provide(:title, 'Редактирование статьи') %>
<div class="center hero-unit">
<%= form_for :service, url: service_path(@service), method: :patch do |f| %>
  <% if @service.errors.any? %>
  <div id="error_explanation">
    <h2> Статя не может быть сохранена из-за следующих <%= pluralize(@service.errors.count, "ошибок")%>: </h2>
    <ul>
    <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
      <%= f.label :"Заголовок" %>
      <%= f.cktext_area :title %>
      <%= f.label :"Позиция заголовка в перечне услуг" %>
      <%= f.text_field  :position %>
      <%= f.label :"Тип оказываемой услуги(МСП, ДСВ и другие)" %>
      <%= f.text_field  :type_service %>
      <%= f.submit :"Сохранить" %>
<% end %>
<%= link_to 'Назад', services_path %>
</div>

app/views/services/index.html.erb
<% provide(:title, 'Перечень услуг') %>
<div class="hero-unit center">
<table>
  <div class="row"><div class="alert alert-success" role="alert"><h3 class="center_align">Меры социальной поддержки</h3></div></div>
  <% @service.each do |elem| %>
      <td><%= link_to  elem.title.html_safe,  service_path(elem), class: "href" %></td>
      <% if sign_in_admin? || sign_in_editor? %>
      <td><%= link_to 'Редактировать', edit_service_path(elem) %></td>
      <td><%= link_to 'Удалить', service_path(elem),
          method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      <% end %>
      <tr></tr>
  <% end %>
<% if sign_in_admin? || sign_in_editor? %>
   <%= link_to 'Новая статья', new_service_path %>
<% end %>
</table>
</div>

app/views/services/new.html.erb
<% provide(:title, 'Новая статья') %>
<div class="hero-unit center">
<%= form_for :service, url: services_path do |f| %>
 <% if @service.errors.any? %>
  <div id="error_explanation">
    <h2>статья не может быть сохранена из-за следующих: <%= pluralize(@service.errors.count, "ошибок") %> </h2>
    <ul>
    <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <p>
    <% end %>
    <%=f.cktext_area :title %>
  </p>
  <%= f.label :"Позиция заголовка в перечне услуг" %>
  <%= f.text_field  :position %>
  <%= f.label :"Тип оказываемой услуги(МСП, ДСВ и другие)" %>
  <%= f.text_field  :type_service %>
  <%= f.submit :"Сохранить" %>
<% end %>
<%= link_to 'Назад', services_path %>
</div>

app/views/services/show.html.erb
<% provide(:title, 'Перечень услуг') %>
<% content_for :description do %>
  <%= meta_description(@content.title) %>
<% end %>

<div class="hero-unit center">
  <div class="row">
    <ul id="nav_list_first" class="nav_list">

     <% @service.sort_by {|x| x.created_at }.each do |elem| %>
        <li><a href="#"><%= elem.title.html_safe %></a>
          <ul>
            <li><a href="#"><%= elem.text.html_safe %> </a></li>
          </ul>
        </li>
      <% end %>

   </ul>

  <%= link_to 'Назад', services_path %>

  <% if sign_in_admin? || sign_in_editor? %>
  <%= link_to 'Добавить запись', new_servicetext_path(params[:id]) %>
  <%= link_to 'Редактировать', servicetexts_path(params[:id]) %>
  <% end %>
  </div>
</div>