config/routes.rb
Rails.application.routes.draw do
  resources :balance_informations
  resources :aboute_posts
  resources :social_posts
  resources :size_pays
  resources :social_services
  resources :payment_infos
  resources :questions
  resources :question_groups
  mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
 
 
  match '/home', to: 'esrc_zbp#homes', via: 'get'
  match '/signup',  to: 'users#new',  via: 'get'
  match '/contacts',  to: 'esrc_zbp#contacts',  via: 'get'
  
  get '/googlee92ee49ba651f9de', :to => redirect('/googlee92ee49ba651f9de.html')

  get '/robots.txt' => 'esrc_zbp#robots'

  resources :articles
  match '/articles',  to: 'esrc_zbp#articles',  via: 'get'
  
  resources :services
  match '/services',  to: 'esrc_zbp#services',  via: 'get'

  resources :servicetexts
  match '/servicetexts',  to: 'esrc_zbp#servicetexts',  via: 'get'

  resources :users
  match '/users',  to: 'esrc_zbp#users',  via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :filials
  match '/filials', to: 'esrc_zbp#filials', via: 'get'

  resources :aboutes
  get '/aboutes', to:  redirect('/aboutes/1'), via: 'get'

  resources :votes
  match '/votes', to: 'esrc_zbp#votes', via: 'get'

  resources :news
  match '/news', to: 'esrc_zbp#news', via: 'get'

  resources :answerposts do
    collection do
    get :index_admin
    end
    member do
    get :answer
    end  
  end
  match '/answerposts', to: 'esrc_zbp#answerposts', via: 'get'

end

app/models/answerpost.rb
class Answerpost < ActiveRecord::Base
	belongs_to :user
end

app/controllers/answerposts_controller.rb
class AnswerpostsController < ApplicationController
	before_action :sign_in_admin, only: [:index_admin, :answer, :destroy]
	before_action :sign_in, only: [:index]
	def new
		@answerpost = Answerpost.new
	end

	def create
		@answerpost = current_user.answerposts.create(answerpost_params)
		if @answerpost.save
			RespondentMailer.new_question(current_user).deliver_now
			redirect_to @answerpost
		else
			render 'new'
		end
	end

	def edit
		if sign_in_admin?
			@answerpost = Answerpost.find(params[:id])
		else
			@answerpost = current_user.answerposts.find(params[:id])
		end
	end

	def show
		if sign_in_admin? || sign_in_respondent?
			@answerpost = Answerpost.find(params[:id])
		else
			@answerpost = current_user.answerposts.find(params[:id])
		end
	end

	def index
		@answerpost = current_user.answerposts.sort_by {|x| x.created_at }.reverse
	end

	def index_admin
		@answerpost = Answerpost.all.sort_by {|x| x.created_at }.reverse
	end

	def answer
		@answerpost = Answerpost.find(params[:id])
	end

	def update
		@answerpost = Answerpost.find(params[:id])
		if @answerpost.update(answerpost_params)
			redirect_to @answerpost
		else
			render 'edit'
		end
	end

	def destroy
		@answerpost = Answerpost.find(params[:id])
		redirect_to @answerpost if @answerpost.destroy
	end

private
	def answerpost_params
		params.require(:answerpost).permit(:title, :text, :answer)
	end

	def sign_in_admin
    redirect_to root_url, notice: "Страница не найдена" unless sign_in_admin? || sign_in_respondent?
  end

  def sign_in
  	redirect_to signin_url, notice: "Вы не авторизованы" unless sign_in?
  end
end

app/views/answerposts/answer.html.erb
<% provide(:title, 'Ответ на вопрос') %>
<div class="center hero-unit">
<%= form_for :answerpost, url: answerpost_path(@answerpost), method: :patch do |f| %>
  <% if @answerpost.errors.any? %>
  <div id="error_explanation">
    <h2> Сохранить не возможно из-за следующих <%= pluralize(@answerpost.errors.count, "ошибок")%>: </h2>
    <ul>
    <% @answerpost.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
   <%= f.label :"Текст" %>
   <%= f.text_field :text, :size => "30x10" %><br>
   <%= f.label :"Текст ответа" %>
   <%= f.cktext_area :answer %>
   <%= f.submit :"Сохранить"%>
<% end %>
<%= link_to 'Назад', index_admin_answerposts_path %>
</div>
  <% if current_user && sign_in_admin? %>
<%= link_to 'Редактировать', edit_answerpost_path(@answerpost) %>
<% end %>
</div>

app/views/answerposts/edit.html.erb
<% provide(:title, 'Редактирование статьи') %>
<div class="center hero-unit">
<%= form_for :answerpost, url: answerpost_path(@answerpost), method: :patch do |f| %>
  <% if @answerpost.errors.any? %>
  <div id="error_explanation">
    <h2> Статя не может быть сохранена из-за следующих <%= pluralize(@answerpost.errors.count, "ошибок")%>: </h2>
    <ul>
    <% @answerpost.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
    <%= f.label "Текст"%>
    <%= f.text_field :text %>
    <%= f.submit :"Сохранить" %>
<% end %>
<%= link_to 'Назад', index_admin_answerposts_path %>
</div>

app/views/answerposts/index.html.erb
<% provide(:title, 'Личный кабинет') %>
<div class="hero-unit center">
   <table id="answerlist">
     <% @answerpost.each do |post| %>

     <% if post.text.size > 40 %>
     <td><%= link_to post.text[0, 40].html_safe << "...", answerpost_path(post) %></td>
     <% else %>
     <td><%= link_to post.text.html_safe, answerpost_path(post) %></td>
     <% end %>

     <td><%= link_to post.created_at.strftime("%d/%m/%Y"), answerpost_path(post) %></td>
         <% if current_user && sign_in? %>
     <td><%= link_to 'Редактировать', edit_answerpost_path(post) %></td>
     <td><%= link_to 'Удалить', answerpost_path(post),
                      method: :delete, data: { confirm: 'Вы уверены?' } %></td>
         <% end %> 
      <tr></tr>      
      <% end %>
  </table>     

  <% if current_user &&  sign_in_admin? || sign_in_respondent? %></br> 
    <%= link_to 'Посмотреть все вопросы', index_admin_answerposts_path %>  
  <% end %>
	
	<% if current_user && sign_in? %></br>
	  <%= link_to 'Задать вопрос', new_answerpost_path, class: "btn" %>
	<% end %>
</div>

app/views/answerposts/index_admin.html.erb
<div class="hero-unit center">
  <table id="answerlist">
    <% @answerpost.each do |post| %>
      <% if post.text.size > 40 %>
      <td><%= link_to post.text[0, 40].html_safe << "...", answerpost_path(post) %></td>
      <% else %>

      <td><%= link_to post.text.html_safe, answerpost_path(post) %></td>
      <% end %>

      <td><%= link_to post.user.name, answerpost_path(post) %></td>

      <td><%= link_to post.created_at.strftime("%d/%m/%Y"), answerpost_path(post) %></td>

      <% if current_user && sign_in_admin? %>
      <td><%= link_to 'Ответить', answer_answerpost_path(post) %></td>
      <td><%= link_to 'Удалить', answerpost_path(post),
        method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      <% elsif current_user && sign_in_respondent? %>
      <td><%= link_to 'Ответить', answer_answerpost_path(post) %></td>
      <% end %>   
      <tr></tr>
      <% end %>
  </table>
</div>

app/views/answerposts/new.html.erb
<% provide(:title, 'Новая статья') %>
<div class="hero-unit center">
    <%= form_for :answerpost, url: answerposts_path do |f| %>
      <% if @answerpost.errors.any? %>
              <div id="error_explanation">
                <h2>статья не может быть сохранена из-за следующих: <%= pluralize(@answerpost.errors.count, "ошибок") %> </h2>
                <ul>
                  <% @answerpost.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
        <% end %>
      <%= f.label :"Текст" %>
      <%= f.text_area :text, :size => "30x10" %>
      <%= f.submit :"Отправить", class: "btn" %>
      <% end %>
<%= link_to 'Назад', answerposts_path %>
</div>

     

app/views/answerposts/show.html.erb
<div class="hero-unit center">
Ворос
  <div id="answerbox"><%= @answerpost.text.html_safe %></div>
Ответ
  <div id="answerbox">
  <%= "Ваш вопрос еще обрабатывается" if @answerpost.answer.nil? || @answerpost.answer.size == 0 %>  
  <%= @answerpost.answer.html_safe if !@answerpost.answer.nil? %>
  </div>
</p>
<br>
  <%= link_to 'Назад к вашим вопросам', answerposts_path %><br>
  <%= link_to 'Назад ко всем вопросам', index_admin_answerposts_path if current_user && sign_in_respondent? %>
  <% if current_user && sign_in_admin? %>
  <%= link_to 'Редактировать', edit_answerpost_path(@answerpost) %>
  <% end %>
</div>