config/routes.rb
Rails.application.routes.draw do
  resources :balance_informations
  resources :aboute_posts
  resources :social_posts
  resources :size_pays
  resources :social_services
  resources :payment_infos
  resources :questions
  resources :question_groups
  mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
 
 
  match '/home', to: 'esrc_zbp#homes', via: 'get'
  match '/signup',  to: 'users#new',  via: 'get'
  match '/contacts',  to: 'esrc_zbp#contacts',  via: 'get'
  
  get '/googlee92ee49ba651f9de', :to => redirect('/googlee92ee49ba651f9de.html')

  get '/robots.txt' => 'esrc_zbp#robots'

  resources :articles
  match '/articles',  to: 'esrc_zbp#articles',  via: 'get'
  
  resources :services
  match '/services',  to: 'esrc_zbp#services',  via: 'get'

  resources :servicetexts
  match '/servicetexts',  to: 'esrc_zbp#servicetexts',  via: 'get'

  resources :users
  match '/users',  to: 'esrc_zbp#users',  via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :filials
  match '/filials', to: 'esrc_zbp#filials', via: 'get'

  resources :aboutes
  get '/aboutes', to:  redirect('/aboutes/1'), via: 'get'

  resources :votes
  match '/votes', to: 'esrc_zbp#votes', via: 'get'

  resources :news
  match '/news', to: 'esrc_zbp#news', via: 'get'

  resources :answerposts do
    collection do
    get :index_admin
    end
    member do
    get :answer
    end  
  end
  match '/answerposts', to: 'esrc_zbp#answerposts', via: 'get'

end

app/models/new.rb
class New < ActiveRecord::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def new
		@new = New.new
	end
	def create
		@new = New.new(new_params)
		if @new.save
    redirect_to @new
  		else
    render 'new'
  		end
	end
	def show
		@new = New.find(params[:id])
	end
	def index
		@new = New.all
	end
	def edit
		@new = New.find(params[:id])
	end
	def update
		@new = New.find(params[:id])
		if @new.update(new_params)
			redirect_to @new
		else
			render 'edit'
		end
	end

	def destroy
  		@new = New.find(params[:id])
 		redirect_to @new if @new.destroy 
  	end

private
	def new_params
	params.require(:new).permit(:title, :text)
	end
end

app/views/news/edit.html.erb
<% provide(:title, 'Редактирование статьи') %>
<div class="center hero-unit">
<%= form_for :service, url: service_path(@service), method: :patch do |f| %>
  <% if @service.errors.any? %>
  <div id="error_explanation">
    <h2> Статя не может быть сохранена из-за следующих <%= pluralize(@service.errors.count, "ошибок")%>: </h2>
    <ul>
    <% @service.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
     <center style="color:blue;"><%= f.label :"Заголовок" %></center><br>
    <%= f.cktext_area :title, :ckeditor => {:uiColor => '#0076cc'} %>
  </p>
   <p>
    <%= f.cktext_area :text, :ckeditor => {:uiColor => '#0076cc'} %>
   </p>
   <p>
    <%= f.submit :"Сохранить"%>
  </p>
<% end %>
<%= link_to 'Назад', services_path %>
</div>

app/views/news/index.html.erb
<% provide(:title, 'Новости') %>
<div class="hero-unit center">
<div class="blok">
<p>Архив новостей</p><div></div><div></div>
</div>
<table>
  
  <% @new.sort.in_groups_of(3, false) do |new| %>
    <% new.each do |elem| %>
       <td style="width:400px;"><%= link_to  elem.title.html_safe,  new_path(elem), class: "href" %>
                <% if current_user && sign_in_admin? %>
                <%= link_to 'Редактировать', edit_new_path(elem) %>
                <%= link_to 'Удалить', new_path(elem),
                    method: :delete, data: { confirm: 'Вы уверены?' } %> 
                <% end %>
        </td>          
    <% end %>        
    <tr></tr>
  <% end %>
<% if current_user && sign_in_admin? %>
<%= link_to 'Новая статья', new_news_path %>
<% end %>
</table>
</div>

app/views/news/new.html.erb
<% provide(:title, 'Новая статья') %>
<div class="hero-unit center">
<%= form_for :news, url: news_index_path do |f| %>
 <% if @new.errors.any? %>
  <div id="error_explanation">
    <h2>статья не может быть сохранена из-за следующих: <%= pluralize(@new.errors.count, "ошибок") %> </h2>
    <ul>
    <% @new.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
    <% end %>
    <p>
    Заголовок
    <%= f.text_field :title, :class => "comments"  %>
  </p>
  <%= f.cktext_area :text, :ckeditor => {:uiColor => '#0076cc'} %>
  <%= f.submit :"Сохранить" %>
<% end %>
<%= link_to 'Назад', news_index_path %>
</div>

app/views/news/show.html.erb
<% provide(:title, 'Новости') %>
<div class="hero-unit center">
<p>
  <strong>Заголовок:</strong>
  <%= @service.title.html_safe %>
</p>
 
<p>
  <strong>Текст:</strong>
  <%= @service.text.html_safe %>
</p>
<%= link_to 'Назад', services_path %>
  <% if current_user && sign_in_admin? %>
<%= link_to 'Редактировать', edit_service_path(@service) %>
<% end %>
</div>