config/routes.rb
Rails.application.routes.draw do
  resources :balance_informations
  resources :aboute_posts
  resources :social_posts
  resources :size_pays
  resources :social_services
  resources :payment_infos
  resources :questions
  resources :question_groups
  mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
 
 
  match '/home', to: 'esrc_zbp#homes', via: 'get'
  match '/signup',  to: 'users#new',  via: 'get'
  match '/contacts',  to: 'esrc_zbp#contacts',  via: 'get'
  
  get '/googlee92ee49ba651f9de', :to => redirect('/googlee92ee49ba651f9de.html')

  get '/robots.txt' => 'esrc_zbp#robots'

  resources :articles
  match '/articles',  to: 'esrc_zbp#articles',  via: 'get'
  
  resources :services
  match '/services',  to: 'esrc_zbp#services',  via: 'get'

  resources :servicetexts
  match '/servicetexts',  to: 'esrc_zbp#servicetexts',  via: 'get'

  resources :users
  match '/users',  to: 'esrc_zbp#users',  via: 'get'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  resources :filials
  match '/filials', to: 'esrc_zbp#filials', via: 'get'

  resources :aboutes
  get '/aboutes', to:  redirect('/aboutes/1'), via: 'get'

  resources :votes
  match '/votes', to: 'esrc_zbp#votes', via: 'get'

  resources :news
  match '/news', to: 'esrc_zbp#news', via: 'get'

  resources :answerposts do
    collection do
    get :index_admin
    end
    member do
    get :answer
    end  
  end
  match '/answerposts', to: 'esrc_zbp#answerposts', via: 'get'

end

app/models/social_service.rb
class SocialService < ActiveRecord::Base
  has_many :social_posts, dependent: :destroy
  accepts_nested_attributes_for :social_posts, :allow_destroy => true
  validates :name, presence: true
end

app/controllers/social_services_controller.rb
class SocialServicesController < ApplicationController
  before_action :set_social_service, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_admin, only: [:new, :create, :update, :destroy]

  def index
    @social_services = SocialService.all
  end

  def show
    @social_service_posts = @social_service.social_posts
    @content = @social_service
  end

  def new
    @social_service = SocialService.new
    @social_service.social_posts.build
  end

  def edit
  end

  def create
    @social_service = SocialService.new(social_service_params)
    if @social_service.save
      redirect_to @social_service
    else
      render :new
    end
  end

  def update
    if @social_service.update(social_service_params)
      redirect_to @social_service
    else
      render :edit
    end
  end

  def destroy
    redirect_to @social_service if @social_service.destroy
  end

  private
    def set_social_service
      @social_service = SocialService.find(params[:id])
    end

    def sign_in_admin
      redirect_to root_url, notice: "Страница не найдена" unless sign_in_admin? || sign_in_editor?
    end

    def social_service_params
      params.require(:social_service).permit(:name, social_posts_attributes: [:title, :text, :social_service_id])
    end
end

app/views/social_services/edit.html.erb
<div class="hero-unit center">
  <h3>Редактировать</h3>

  <%= render 'form' %>

  <%= link_to 'Назад', @social_service %> |
  <%= link_to 'На главную', social_services_path %>
</div>

app/views/social_services/index.html.erb
<% provide(:title, 'Социальная защита населения') %>
<div class="hero-unit center">
  <div class="row">
    <div class="alert alert-success" role="alert"><h3 class="center_align">Социальная защита населения</h3></div>
  </div>
  <p id="notice"><%= notice %></p>
    <table>
      <% @social_services.each do |social_service| %>
        <tr>
          <td><%= link_to social_service.name.html_safe, social_service %></td>
          <% if sign_in_admin? || sign_in_editor? %>
            <td><p><%= link_to 'Редактировать', edit_social_service_path(social_service) %></p></td>
            <td><p><%= link_to 'Удалить', social_service, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить?' } %></p>
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <br>
    <% if sign_in_admin? || sign_in_editor? %>
      <%= link_to 'Добавить', new_social_service_path %>
    <% end %>
</div>

app/views/social_services/new.html.erb
<% provide(:title, 'Новая запись') %>
<div class="hero-unit center">
<h3>Основной заголовок</h3>

<%= render 'form' %>

<%= link_to 'Назад', social_services_path %>
</div>

app/views/social_services/show.html.erb
<% provide(:title, 'Социальная защита населения') %>
<% content_for :description do %>
  <%= meta_description(@content.name) %>
<% end %>

<div class="hero-unit center">
 <div class="row">
  <ul id="nav_list_first" class="nav_list">
    
    <p>
    <% @social_service_posts.each do |post| %>
      <li><a href="#"><%= post.title.html_safe %></a>
        <ul><li><a href="#"><%= post.text.html_safe %></a></li></ul>
      </li>
    <% end %>
  </ul>
  </p>
  <% if sign_in_admin? || sign_in_editor? %>
    <%= link_to 'Добавить', new_social_post_path(id: @social_service) %>
    <%= link_to 'Редактировать', social_posts_path(id: @social_service) %>
  <% end %>
  <%= link_to 'Назад', social_services_path %>
  </div>
</div>